import { orderItemInterface } from "../interfaces/order";

const orderItems: orderItemInterface[] = [
	{
		id: 1,
		reference: "buybubudbu",
		new: true,
		price: 3000,
		payment: "Paypal",
		status: "pending",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 2,
		reference: "buybubudbu",
		new: true,
		price: 3000,
		payment: "Check",
		status: "pending",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 3,
		reference: "buybubudbu",
		new: false,
		price: 3000,
		payment: "Paystack",
		status: "paid",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 4,
		reference: "buybubudbu",
		new: false,
		price: 3000,
		payment: "Check",
		status: "paid",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 5,
		reference: "buybubudbu",
		new: true,
		price: 3000,
		payment: "Check",
		status: "pending",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 6,
		reference: "buybubudbu",
		new: false,
		price: 3000,
		payment: "Flutterwave",
		status: "failed",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 7,
		reference: "buybubudbu",
		new: true,
		price: 3000,
		payment: "Paypal",
		status: "failed",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
	{
		id: 8,
		reference: "buybubudbu",
		new: true,
		price: 3000,
		payment: "Paystack",
		status: "paid",
		name: "Mathias Roy",
		email: "emsthias33@gmail.com",
		Address: "Ikeja Lagos",
	},
];

export default orderItems;
